### ISSUE TITLE
Usage help

### ISSUE THREAD

**Issue by palica** [dhaavi/caddy-permission#1]
Hi dhaavi,

I like your forum post at https://caddy.community/t/improve-caddy-auth-system/2688

Could you please give me some instructions as how to add this plugin to caddy and how to use it in config file?

Thank you in advance

**Comment by dhaavi** [comment]
Hey palica,

I just added a first README. Check it out!
If something is unclear, please just respond here.

**Comment by palica** [comment]
Hey dhaavi,

thank you for the initial usage stuff. Where I have missing knowledge is how to add this to caddy? Maybe you can point me to some caddy documentation. Or write simple howto compile and add to caddy?

Thank you in advance!

**Comment by dhaavi** [comment]
I just added this to the README:

To build a caddy server just with authplugger as a plugin (and no others), go into the `test` directory and execute `go build simple.go`, the resulting file `simple` is your binary.

Note, that you will have to `go get` any missing "libraries", such as caddy itself!

**Comment by palica** [comment]
OK, going to try it out and let you know/ask for more help.

Thank you!

**Comment by palica** [comment]
Hey dhaavi,

I was able to compile it using simple.go

Here is what I had to do:
```
mkdir -p ~/go
export GOPATH=~/go
go get github.com/mholt/caddy/caddy
go get github.com/caddyserver/builds
go get github.com/dhaavi/caddy-authplugger
mv ~/go/src/github.com/dhaavi/caddy-authplugger ~/go/src/github.com/dhaavi/authplugger
go get github.com/xenolf/lego/acme
go get gopkg.in/natefinch/lumberjack.v2
cd ~/go/src/github.com/dhaavi/authplugger/test
go build simple.go
```

I have a couple of questions/notes.

caddy -plugins and simple -plugins differ in Other plugins - simple doesn't have shutdown, startup. I don't know if that is needed or not for something.

And I also got this notice upon starting the binary:
[DEV NOTICE] Registered directive 'authplugger' before 'basicauth'

Going to try to configure it and will let you know.

Thank you so far.

**Comment by palica** [comment]
Testing settings:

specifying methods like this didn't work for me
```
...
public
GET,POST,PUT,HEAD /
...
```
I still got 401 on GET
Am I doing it wrong?

**Comment by dhaavi** [comment]
I just tested with this config file, worked perfectly:

```
localhost

browse

authplugger realm AuthPluggerTest
authplugger allow_reading_parent_paths

authplugger basic {
  user greg password
  rw /secret/

  * # or "default"
  rw /internal/

  ! # or "public"
  ro /static
  ro /sw.js
  ro /api/auth/renew
  rw /api/users/0
  GET,HEAD /
}
```

Are there any log messages?
Can you paste the exact Caddyfile you used?

**Comment by palica** [comment]
```
http://elk:9200 {
  proxy / http://10.208.254.37:9200 {
    header_upstream Host {host}
    transparent
  }
  timeouts none
  gzip
  authplugger basic {
    public
    GET,POST,PUT,HEAD /
  }
}
```

**Comment by dhaavi** [comment]
Thank you. This is interesting. I will investigate further tomorrow.

**Comment by palica** [comment]
I want to disallow DELETE method for Elasticsearch but want to allow the other methods.

**Comment by dhaavi** [comment]
I fixed it. Should work now.

If you really only want to disallow `DELETE`, you could also use

```
public
~DELETE /
```
Although I should note, that
```
public
GET,POST,PUT,HEAD /
```
is more secure (because whitelisting is almost always better).

**Comment by palica** [comment]
Thanks dhaavi, for the fix and support.
